language: python

python:
  - 2.7
  - 3.3
  # Current incompatible with pinned scikit-learn version
  #- 3.4

install:
  - conda update conda --yes
  - conda create -n testenv --yes pip python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  - conda install --yes ipython numpy scipy nose matplotlib pandas statsmodels scikit-learn six
  - pip install seaborn
  - pip install nibabel
  - pip install .

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/anaconda/bin:$PATH

script: nosetests
